### ISSUE TITLE
acceptance prerequisite: data_ingress_v1: 1 - data fixtures

### ISSUE THREAD

**Issue by mikeAdamss** [ONSdigital/dp-data-pipelines#38]
## What is this

We're going to want to run acceptance tests that check that the transform pipelines are doing what they're supposed to be doing. Which can lead to source control issues (you don't want gigs of test data in your repo).

This task is to create the functionality to create data test fixture so we can handle this in a sustinable way.

## What to do

This is a skeleton acceptance test.

```yaml
Feature: Data Ingress v1
  As a data engineer I want a configurable pipeline that..
  - can confirm correct configuration and inputs
  - can send sending notifications in the event of issues
  - can successfully transform input into rexpected outputs
  - will call the required apis to pass along these outputs
  - will notify publishing that a resource is ready for publishing

  # TODO - this will grow in time to encapsulate the happy path for the above
  Scenario: Pipeline runs without errors
    Given a temporary source directory of files
        | file                   |  fixture                           |
        | pipeline-config.json   |  pipeline_config_basic_valid.json  |
        | data.sdmx              |  data_sdmx_valid_1.sdmx            |
    And v1_data_ingress starts using the temporary source directory

```

What we want is:

#### 1.1 A zip of data, just use 1 random (small) sdmx fie file for developing

store it in `./fixtures/data-fixtures.zip` and call it `sdmx_data_sdmx_valid_1.sdmx` (we'll renamed or replace it in later tasks).

#### 1.2 Create a pipeline config fixture

A fixture like the above but just return a json config. Json is light weight but given we've established a compression mechanism it way as well also go in the zip.

#### 1.3 Create `./features/environment.py`

Add a [before_all](https://github.com/GSS-Cogs/idpd-navigation-proxy/blob/071a3630bfc0be85c0168c46e348d639bcab77c1/tests/features/environment.py#L9) statement to it.

Your `before_all` function should unzip `./fixtures/data.zip` into the directory `./fixtures/data` if it does not yet exist.

### 2.0 Feature skeleton

- add the yaml snippet on this task as `/features/data_ingress_v1.yml`
- install behave
- run behave - that should give you the step functions with `NotImplementedError` in them
- put this step in a file `/features/steps/data.py`
- use the dictionary (denoated by the table, all those '|'s in the yaml) to copy the fixtures requested (guidance on reading tables below) into a temporary directory.
- start the function `v1_data_ingress()` using the `Path` to this temporary directory - [this](https://github.com/ONSdigital/dp-data-pipelines/blob/sandbox/pipelines/pipeline/dataset_ingress_v1.py).

Note: to get keys and values out of a table do something [like this](https://github.com/GSS-Cogs/idpd-navigation-proxy/blob/071a3630bfc0be85c0168c46e348d639bcab77c1/tests/features/steps/proxy.py#L39) - just remember its "file" and "fixture" not "key" and "value" here.

## Accpeptance Criteria

- [x] Acceptance test data is stored as a zip
- [x] The skeleton acceptance test will unzip if the unzipped version is not on the machine in question
- [x] the uncopmpressed data assets can be accessed via fixtures
- [ ] The skeleton acceptance test can populate the temporart directory using the specified fixtures
- [ ] We can create a temp directory with the files in it.
